### ISSUE TITLE
[windows] can't go up past c:/ level

### ISSUE THREAD

**Issue by adrianstaniec** [punassuming/ranger.el#100]
on windows it is not possible to change partitions using hjkl

so when I start in c:/Users/adrta i press `h` twice to go to c:/
but the third time has no effect, actually it duplicates the buffer with c:/ contents

however, I would expect instead to see a buffer with this list:
c:
d:
e:
f:

I am on:
Microsoft Windows 7 Home Premium
6.1.7601 Service Pack 1 Build 7601
"GNU Emacs 24.5.1 (x86_64-w64-mingw32)
 of 2015-05-16 on KAEL"
Spacemacs v.0.105.11

**Comment by punassuming** [comment]
@adrsta, this is how dired works, I am trying out an option now that will allow you to choose from the other drives.

**Comment by punassuming** [comment]
@adrsta, I added functionality to navigate windows drives with `gD`.  Also moving up directories past root should show the same thing.

**Comment by adrianstaniec** [comment]
Not bad at all ;)
Thanks man, you rock! :+1:

**Comment by punassuming** [comment]
Thanks =)
