### ISSUE TITLE
deer causes helm-descbinds to open in a new frame

### ISSUE THREAD

**Issue by alphapapa** [punassuming/ranger.el#111]
When I run `helm-descbinds` from a ranger buffer, the Helm buffer is opened in a new frame.  The buffer in the new frame is showing the `helm-descbinds` content, but it's not in Helm mode; it's a plain buffer that can be edited.

In `*Messages*` I see this:

```
Ranger window was overwritten. Redirecting window to new frame
```

Thanks for your work on ranger.

**Comment by punassuming** [comment]
@alphapapa, thanks for the comment, but this does not happen for me. Do you have a window manager running like popwin?

**Comment by alphapapa** [comment]
Hm, that's strange.  AFAIK the only thing like that I have is `shackle`, but I've been using it for years and it doesn't cause problems with anything else.

**Comment by punassuming** [comment]
Yeah, I have seen problems with shackle as well.  Ranger is trying to control the window placement and so is shackle.  I will look into how to nake them work together

**Comment by alphapapa** [comment]
I'm sorry, I just realized, it's `deer` that does this, not `ranger`.  I used `deer` in a new Emacs profile and reproduced it.  It happens without `shackle`.

It also causes `packages-list-packages` to open in a new frame.

**Comment by punassuming** [comment]
@alphapapa, =( I still don't get it in either.  `deer` especially should not be causing this behaviour.  Even with `shackle-mode` on.  Can you tell me which version of `ranger.el` you have running.  Are you using `melpa-stable` or `melpa`?

**Comment by alphapapa** [comment]
I just made a fresh MELPA sandbox and installed `ranger` and `helm-descbinds` from MELPA, so they should be the current versions of both.  Then I ran `deer`, then `helm-descbinds`, and it opened Helm in a new frame saying `Ranger window was overwritten. Redirecting window to new frame`.  I'm using Emacs 24.4 on Ubuntu Trusty, package version `24.4+1-5`.

**Comment by punassuming** [comment]
@alphapapa, I checked the `helm-descbinds` package and found that it is basically clearing all windows with the default setting.  I have found that setting `(setq helm-descbinds-window-style 'same-window)` seems to work.

**Comment by punassuming** [comment]
@alphapapa, I added some comments on dealing with various packages in the help documentation to try to address this gap.  Thanks for letting me know about it.

**Comment by alphapapa** [comment]
@ralesi Hmm, ok.  But what about `package-list-packages`?  That's part of Emacs.
