### ISSUE TITLE
.DS_Store not excluded

### ISSUE THREAD

**Issue by hiaw** [punassuming/ranger.el#114]
In OSX there is always a .DS_Store for each folder. This is a binary file that contains the attribute for that folder. I would like to exclude that instead of being shown gibberish.

I set

```
  (setq ranger-excluded-extensions '("DS_Store"
                                     "mkv" "iso" "mp4" "bin" "exe" "msi"))
```

But it stills show the .DS_Store file. Note that I would like to keep `ranger-show-dotfiles` option as I work with the .gitignore, .zshrc etc regularly.

**Comment by punassuming** [comment]
@hiaw, the exclude parameter specifically just does not show previews for the file.

**Comment by punassuming** [comment]
If you want to hide the file from showing at all,  use `ranger-hidden-filter`

**Comment by hiaw** [comment]
Thanks
