### ISSUE TITLE
ranger-show-literal cause persisting header

### ISSUE THREAD

**Issue by hiaw** [punassuming/ranger.el#115]
I set `(setq ranger-show-literal t)` so that it will have nice syntax highlighting by default as I go through the file list. It causes the following where the file path is constantly visible on the first line. 

<img width="714" alt="screenshot 2016-04-14 06 39 33" src="https://cloud.githubusercontent.com/assets/527296/14505411/1d281586-020d-11e6-96e4-b74a444a9a20.png">

Reproduce:
- `(setq ranger-show-literal t)` in `.spacemacs`
- restart spacemacs, select a recent file
- open ranger to open another file
- the the first line is occupied by the file path

**Comment by punassuming** [comment]
@hiaw, Fix is in to revert `header-line-format` when used.

**Comment by hiaw** [comment]
Confirm fix. Thanks.

**Comment by rbugajewski** [comment]
I use `ranger-20210125.330` and I currently experience the same issue. Is there any information I can provide that would help with debugging?

**Comment by rbugajewski** [comment]
While not really a solution, a fast workaround is to kill the buffer from where you started ranger, as this is just a local variable, and other buffers aren’t affected.

**Comment by rbugajewski** [comment]
After investigating this issue, it is slightly different. I have `(ranger-show-literal nil)` in order to see previews, and the header line stays when I quit ranger. When I open a file as described in the original issue, the header line correctly reverts.

@ralesi Should I open another issue or is it part of this one as it is related to the header line not reverting?

**Comment by rbugajewski** [comment]
OK, it is slightly more complicated than I initially thought. When I launch ranger from certain major modes like `vterm-mode` or `circe-mode` the header line is correctly reverted, but when I launch ranger from `org-mode` it will stay after I quit ranger.
