### ISSUE TITLE
ranger-cleanup-on-disable

### ISSUE THREAD

**Issue by Wicus** [punassuming/ranger.el#116]
ranger-cleanup-on-disable doesn't clean Dired buffers after quitting

**Comment by punassuming** [comment]
@wicus, was this addressed?  Do I still need to look into this?

**Comment by Wicus** [comment]
I'm new to ranger, thought it would automatically clean all opened dired buffers upon quiting ranger, but realized that the setting only cleans ranger buffers and not dired buffers. Would be really nice to have though, because it opens a whole lot of buffers, that I have to go and clean up afterwards.

**Comment by ghost** [comment]
Just thought I'd  add that I am experiencing the same issue, and it is, unfortunately, a significant drawback. I'm sure you have lots  on your plate, and this is a wonderful package regardless, but cleaning up all the detritus from dired would go a long way towards letting this be my primary file manager. If I figure out anything that helps, I'll report back.

Thanks for all the hard work!

**Comment by punassuming** [comment]
@aBathologist, try the latest changes, there should be a lot less buffers appearing when existing ranger.

**Comment by ghost** [comment]
Yay! It's fixed 😄 ! Thank you 🌟
