### ISSUE TITLE
No images preview

### ISSUE THREAD

**Issue by toelle** [punassuming/ranger.el#117]
Switched from peep-dired to ranger.el. But unlike the former ranger.el does not show previews from any picture at any size.

**Comment by punassuming** [comment]
@toelle, do you get the desired functionality when pressing "zi"?

**Comment by toelle** [comment]
Yes, after pressing `zi` it works. Now I understand. I set `ranger-show-literal` to t, which apperently is set to nil per default.
Great thanks, ranger.el rules!

**Comment by punassuming** [comment]
Thanks!  I disabled image preview from the start to speed up navigation.   There is also a image resize toggle that will work if you have ImageMagick installed.

**Comment by vherrmann** [comment]
@ralesi You don't mean ranger-width-preview" with the image resize toggle, do you?
