### ISSUE TITLE
Ranger and Deer clobber header-line-format for calling buffer

### ISSUE THREAD

**Issue by mccullerlp** [punassuming/ranger.el#118]
I'm using ranger/deer from Spacemacs and find that it is resetting my header-line-format (which is using tabbar currently). 

Easy to fix, but strange and inconvenient for it to clobber the calling buffer since ranger generates its own buffers.

Just set header-line-format to something, can quickly test with 

(setq header-line-format mode-line-format) 

then run ranger and reopen the calling buffer from ranger. The header line is reset.

**Comment by punassuming** [comment]
@mccullerlp, yes I don't have anything to address header-lines that are already in place.  I will get a fix in place that will revert the modeline once ranger is escaped.

**Comment by punassuming** [comment]
Fix is in to revert `header-line-format` when used.
