### ISSUE TITLE
cannot open load file: subr-x

### ISSUE THREAD

**Issue by ghost** [punassuming/ranger.el#120]
I am facing issue installing ranger manually
[link](http://emacs.stackexchange.com/questions/22142/cannot-open-load-file-subr-x) to my issue
Is there any way to install it manually

**Comment by punassuming** [comment]
@neelabalan,  it looks like this was resolved within reddit, but if you need more help getting this to work with 24.3, you can try looking at some of the older version tags, where we still supported 24.3 to get some ideas.

**Comment by ghost** [comment]
thanks
