### ISSUE TITLE
Multiple dired buffers uncleaned.

### ISSUE THREAD

**Issue by gujiaxi** [punassuming/ranger.el#122]
When I browse across multiple directories using ranger, it creates multiple dired buffers. I'm not sure if it is the same problem as @Wicus reported in [#116](https://github.com/ralesi/ranger.el/issues/116). It seems that ranger is responsible for cleaning only _ranger buffers_ instead of _dired buffers_ no matter `ranger-cleanup-on-disable` or `ranger-cleanup-eagerly`. Is that so?

Even when I use `(require 'dired-single)` which works in vanilla dired, there are multiple dired buffers left after using ranger.

Thanks for your awesome work.

**Comment by punassuming** [comment]
@gujiaxi, thanks for the comment!  I need to look more in the cleanup methodology.  Let me get back to you when I have refreshed on it.

**Comment by punassuming** [comment]
@gujiaxi, the latest changes improve cleanup, both when `ranger-cleanup-on-disable` or `ranger-cleanup-eagerly` is set.

**Comment by gujiaxi** [comment]
@ralesi It works fine now. Thanks for your work.
