### ISSUE TITLE
support for dired-jump and dired-jump-other-window?

### ISSUE THREAD

**Issue by justbur** [punassuming/ranger.el#123]
I think it's self explanatory but it would be nice to jump to the line corresponding to the current file if possible.

**Comment by punassuming** [comment]
@justbur, this should be the case.  I recently found it was working in Ranger but not deer,  but fixed that over last weekend.  Let me know if this is not working.

**Comment by justbur** [comment]
Hi, I tried again and it's not working. To be specific I enabled `ranger-override-dired` and expected `dired-jump-other-window` to open deer in another window with the current file selected and that's not what is happening. First, it is opening in the same window, and second it is selecting another file.

**Comment by JohnLunzer** [comment]
Also having the same issue. Not sure what version of ranger spacemacs develop is pulling though...

I have ranger-override-dired enabled and I'm using the ranger layer in spacemacs and dired-jump and also when I open a project from the home buffer it's opening up dired instead of deer.

**Comment by punassuming** [comment]
@justbur and @JohnLunzer,  I created a new test function `deer-jump-other-window`.  We should be able to overwrite dired-jump now.  I might change implementation, but please let me know if this works.

**Comment by justbur** [comment]
Seems to work so far for me. Thanks. @ralesi feel free to close this
