### ISSUE TITLE
Copy the path of current selection.

### ISSUE THREAD

**Issue by amosbird** [punassuming/ranger.el#128]
This would be a very convenient method to add path items to some config files.

**Comment by punassuming** [comment]
@amosbird, this is already available in dired (ranger allocates all standard dired bindings under the `;` prefix).  Press `; w` for file name and `C-u ; w` to get the entire path of the filename.

**Comment by amosbird** [comment]
@ralesi Thanks. `C-u 0 ; w` gets the entire path in spacemacs :)

**Comment by ngoonee** [comment]
I recommend that key-bindings be added for ranger-like copying (e.g. 'yp' for path, 'yn' for name), just redirecting to the dired functionality.

**Comment by punassuming** [comment]
Not a bad idea, will see how it would be implemented
