### ISSUE TITLE
Don't show in recentf

### ISSUE THREAD

**Issue by dieggsy** [punassuming/ranger.el#129]
It appears that every file previewed gets added to `recentf`'s list of recent files. It would be nice to have an option (or maybe there is one?) to not add previewed buffers to recentf, since this kind of pollutes the `recentf` list. Not sure if this can be achieved.

**Comment by punassuming** [comment]
@therockmandolinist, recent updates have addressed this.

**Comment by dieggsy** [comment]
Awesome, thanks!
