### ISSUE TITLE
ranger makes the cursor invisible

### ISSUE THREAD

**Issue by jmburgos** [punassuming/ranger.el#137]
Hi Rich,

I just discovered your package.  It is great.  I am thinking about making it my alternative to dired, but I am having a strange issue when I toggle the fully formatted preview of files, either by doing "zi" or by setting the ranger-show-literal to nil.  What happens is that when launch range from a buffer and then exit, the cursor in the original buffer becomes invisible.  This happens only for the buffer where I launched ranger from.  In the other buffers the cursor is fine.

Do you know what could be the cause?
Many thanks!

**Comment by punassuming** [comment]
@jmburgos, I think I have this fixed in the develop branch, can you give it a try when you get a chance?

Thanks for the comments.

**Comment by jmburgos** [comment]
I think you did.  The develop branch works fine, and the cursor does not disappears when toggling the fully formatted preview. Thanks!

**Comment by punassuming** [comment]
Develop now pushed into master.

**Comment by AoifeHughes** [comment]
This has been affecting me - on emacs 25 Linux mint. Melpa version of package.
