### ISSUE TITLE
startup problem: Symbol’s value as variable is void: bookmark-alist

### ISSUE THREAD

**Issue by hyOzd** [punassuming/ranger.el#140]
When I try to start ranger I get this error:

    ranger-mode: Symbol’s value as variable is void: bookmark-alist

It seems `bookmark` module is required for ranger operation. I think this module is loaded automatically in emacs 24 but not in emacs 25. I share the same configuration on different installations and I had this problem only with emacs 25. Adding `(require 'bookmark)` solved it.

**Comment by punassuming** [comment]
@hyOzd thanks for the heads up.  I required `bookmark` in ranger-setup. 4329508c534fe626a6083df39bfe0ec8c75a2dfb
