### ISSUE TITLE
Symbol’s value as variable is void: block when opening file

### ISSUE THREAD

**Issue by emmettu** [punassuming/ranger.el#142]
```
Symbol’s value as variable is void: block
```

This occurs in emacs 25 when trying to open a file, seems almost the same as #140 but with a different package that isn't auto-loaded in 25: cl-macs.

Adding (require 'cl-macs) fixes the problem.

**Comment by odysseyalive** [comment]
(require 'cl-lib)

**Comment by emmettu** [comment]
cl-lib doesn't define the block macro. cl-block is defined in cl-macs.el, and block which is an alias for cl-block is defined in cl.el. For whatever reason neither of these get loaded automatically in emacs 25, so

```
(require 'cl)
```
or
```
(require 'cl-macs)
```
is needed as far as I can tell.

**Comment by odysseyalive** [comment]
Odd, I tried both of those and neither of them worked for me, but cl-lib suppressed the error.  I'm on the brew build of emacs-mac.

**Comment by emmettu** [comment]
What version of emacs is that? I only get the error in emacs 25.

**Comment by odysseyalive** [comment]
25.2.1

**Comment by emmettu** [comment]
Weird. I reinstalled ranger and don't get the error anymore. Maybe something was up with my config. Thanks by the way :+1:
