### ISSUE TITLE
No preview on directories and many errors

### ISSUE THREAD

**Issue by Somelauw** [punassuming/ranger.el#144]
When on a directory, the preview window remains blank.

I also get some errors:
- void-function dired-mark-unmarked-files (when trying to preview a directory)
- void-variable bookmark-alist (when entering a dictionary)
- wrong-type-argument window-valid-p #<window 30> (when toggling preview)
- void-variable ranger-pre-header-format (when previewing an org file)

**Comment by punassuming** [comment]
@Somelauw ,  can you give some more details on these issues? 

What is you build?  Does it happen in every folder?  Can you give a backtrace on any of these issues?

**Comment by Somelauw** [comment]
Emacs 24.5.1 using the spacemacs distribution.

```
Debugger entered--Lisp error: (void-variable ranger-pre-header-format)
  ranger-revert-appearance(#<buffer *spacemacs*>)
  ranger-revert()
  ranger-disable()
  ranger-close()
  call-interactively(ranger-close nil nil)
  command-execute(ranger-close)
```

Following the instructions in this issue https://github.com/syl20bnr/spacemacs/issues/8360, I added:

    (require bookmark)

After doing so, all errors seem to have disappeared.

**Comment by punassuming** [comment]
Can you try updating the package on melpa? I updated yesterday and explicitly required bookmark.

**Comment by Somelauw** [comment]
@ralesi thanks. I have updated it and no longer need to require bookmark myself.
