### ISSUE TITLE
Dotfiles showing after disabling them

### ISSUE THREAD

**Issue by ghost** [punassuming/ranger.el#145]
I have the following in my config.

(setq ranger-show-dotfiles nil)

When I fire up ranger it still shows me dotfiles by default. Am I doing something wrong?

**Comment by punassuming** [comment]
@gregf, sorry about this.  I updated the variable without cleaning up the readme.  Variable should be `ranger-show-hidden`, updated here ccee160894b8e897fa3a651017712ff4a373e508
