### ISSUE TITLE
item rendering is not stable

### ISSUE THREAD

**Issue by amosbird** [punassuming/ranger.el#159]
Sometimes ranger.el looks like this after I did some actions (e.g. delete),
![](https://paste.wentropy.com/CQF7.png)

**Comment by punassuming** [comment]
@amosbird, I reverted my attempt to mask the details in the recent `master`.  Let me know if this helps this issue.

**Comment by amosbird** [comment]
@ralesi thanks. It works nearly as expected now. A minor issue, after directory trashed, `.` and `..` is unmasked.
