### ISSUE TITLE
Attempt to delete minibuffer or sole ordinary window

### ISSUE THREAD

**Issue by psamim** [punassuming/ranger.el#19]
Hi,
I do not what causes the problem but when I add this to my configs, emacs cannot start with the above error.

``` lisp
(add-hook 'dired-mode-hook
          (lambda()
             (ranger)
            (hl-line-mode)))
```

**Comment by punassuming** [comment]
This has to do with the way the window config is saved and windows are set.  I am considering implementing this internally so it could work out of the box.  The goal is to make all dired windows like ranger?  Whats the point of the hl-line-mode call?

**Comment by psamim** [comment]
I wanted "dired-jump" to bring ranger automatically. I changed my mind, now I used "ranger" instead of "dired-jump".

Thanks for your reply.
