### ISSUE TITLE
Can't preview image files in Mac OS

### ISSUE THREAD

**Issue by takedawilliam** [punassuming/ranger.el#192]
When I open an image folder, and go up & down to preview images, it shows the following error:
```
(error "Opened XXX.jpg in external program")
```
No external program shows up. And no preview is displayed inside Emacs.

My env info: Mac OS Mojave

Could you please help me?

**Comment by punassuming** [comment]
@lbkvu do you ever have issues veiwing images in Emacs? Did you install through Brew?

**Comment by takedawilliam** [comment]
Never mind. I can see image preview with Ranger now.

When the above problem happened, I stopped using Ranger. 

Then, I found that I couldn't open images in buffers. Then, after config imagemagick, I can view images.

When I see your comment, I try Ranger again and this time I can see image preview. It must have something to do with imagemagick config.
