### ISSUE TITLE
Add support for bookmarks

### ISSUE THREAD

**Issue by jtbm37** [punassuming/ranger.el#20]
Hi

It would be great if we could navigate to a bookmark `(bookmark-set)`.

I currently use `helm-bookmarks` but it breaks ranger's flow.

Thanks

**Comment by punassuming** [comment]
There are two fixes that I can think of for this.  Do we want to make all dired calls automatically switch to ranger mode,  or just make a ranger specific function to open bookmarks?

**Comment by jtbm37** [comment]
I think they should switch to ranger mode. Maybe we should also provide an escape sequence to execute the dired one. `b` would navigate to bookmarks while `C-u b` would execute the dired bound command.

**Comment by psamim** [comment]
@jtbm37 @ralesi 
I use something similar to original ranger bookmarks as below,  "gh" will go to home directory.

``` elisp
(define-minor-mode psamim-dired-mode
  "Minor mode over dired-mode."
  :keymap (make-sparse-keymap))

(after 'evil
(evil-define-key 'normal psamim-dired-mode-map "gh" (lambda() (interactive) (find-file "~")))

(add-hook 'dired-mode-hook
          (lambda()
            (psamim-dired-mode)))
```

**Comment by punassuming** [comment]
@psamim, I was going to implement a function almost exactly like that. Question: do we want "gh" or "g~"?

**Comment by psamim** [comment]
"gh" is more accessible imho.

**Comment by vyp** [comment]
About the go home function, I also +1 to `gh`. It isn't mapped by evil I think, so it should be fine.

**Comment by punassuming** [comment]
@psamim, @jtbm37 and @vyp
- "gh", "gg", and "G" mappings are here 13865e0e76bcdd6401bb8446c559a16610c5e862
- bookmark support here 13865e0e76bcdd6401bb8446c559a16610c5e862

**Comment by vyp** [comment]
@ralesi Brilliant thanks! But why implement `gg` and `G`? Isn't `evil-goto-first-line` and `evil-goto-line` sufficient?

**Comment by vyp** [comment]
Also I'm assuming it should not be "Move to top of file list" for all three functions.

**Comment by vyp** [comment]
Oh it's because you dropped the evil dependency altogether! My bad.

**Comment by vyp** [comment]
Also, I think you mean https://github.com/ralesi/ranger/commit/88e06c4bc4bb25dde9255857e88f4f6c41151244 for bookmarks.

**Comment by punassuming** [comment]
Can this be closed now?
