### ISSUE TITLE
so many strange behaviors

### ISSUE THREAD

**Issue by gnusupport** [punassuming/ranger.el#206]
I have just downloaded it from MELPA, I think, right now, and so many errors appear.

It looks good, but it is not stable for publishing in MELPA.

Example is `q` as each time I press `q` it opens new buffer with the same directory. I cannot quit.

It opens random directories too.

**Comment by punassuming** [comment]
I don't think I have this behaviour, it seems to work for me. This is from the start? Go to a directory and press q and then it does not quit?

**Comment by gnusupport** [comment]
I installed it again from repository, tried, it works, but when I wish to leave it, the echo area becomes corrupted and the stuff. Is too much for me, I have removed it. Thank you. I hope it will become good in soon future.
