### ISSUE TITLE
Copy/Move workflow

### ISSUE THREAD

**Issue by psamim** [punassuming/ranger.el#21]
In plane dired-mode I used to open two dired panes, and by setting "dired-dwim-target" I could easily copy or move files between two panes (directories). As ranger uses panes itself, I cannot use this method any more. Is there a better way for doing this?

Also in original ranger, I used to copy/move files between two directories using tabs.

**Comment by punassuming** [comment]
@psamim dired-ranger has some functuonality like that,  but its not consistent with the way copy and paste work in ranger.   Hopefully this weekend I will have some time to implement copy and paste rings to dired

**Comment by punassuming** [comment]
@psamim copy functionality has been added. Readme is updated with usage.

**Comment by psamim** [comment]
Thanks @ralesi , I will check it.

**Comment by afermg** [comment]
Just for the record. This is not working in the latest versions.
