### ISSUE TITLE
ranger-paste issue on existing file

### ISSUE THREAD

**Issue by odysseyalive** [punassuming/ranger.el#217]
I'm tracking down the following issue.  If anyone has any thoughts in the meantime - much appreciated.

Receiving the following error when pasting a file in the same directory that the file already exists in:

Copied 1 item(s) to copy ring [total:1]
ranger-paste: Symbol’s value as variable is void: base-target

Under normal operation, the new filename has an underscore appended to the end if the file already exists in the same directory.  This wasn't happening prior to the last update: Version: 20200218.203

Fedora 31
GNU Emacs 28.0.50

Current Configuration:

(use-package ranger :ensure t
  :diminish ranger-mode
  :config
  ;; Add ability to create directory
  (define-key ranger-normal-mode-map (kbd "+") #'dired-create-directory)
  ;; Set as default browser
  (ranger-override-dired-mode t)
  ;; Remove ranger buffer when done
  (setq ranger-cleanup-on-disable t)
  ;; Kill browser buffers when drilling down
  (setq ranger-cleanup-eagerly t))

**Comment by yuhan0** [comment]
This was a regression introduced by #191, perhaps when I rebased it earlier this year to resolve conflicts. I hope this new PR gets merged soon and sorry for the inconvenience!
