### ISSUE TITLE
Ranger side buffers stay around

### ISSUE THREAD

**Issue by justbur** [punassuming/ranger.el#23]
This is just one issue related to going back to a previous layout, but if I `M-x ranger` then use `f` to select a file I still have two ranger buffers on the left. The behavior is different if I scroll down to the file and hit return. In that case, the buffers on the left disappear. I can provide screenshots if you need more detail. Thanks

This is probably harder, but it would be nice if ranger could restore the window layout after I'm done using it.

**Comment by justbur** [comment]
To add to this, it would be nice if `ranger-disable` at least returned you to the buffer you were visiting when `M-x ranger` was executed. Right now for me it sends me to a dired buffer.

**Comment by punassuming** [comment]
@justbur I will think about how to address this.  To me this is the biggest problem because any exit outside of the defined bindings will not revert the buffers.  I have considered advising a lot of functions to compensate but i have yet to find something to force ranger-revert to run when exiting ranger.

**Comment by punassuming** [comment]
@justbur, try out current HEAD 
- modified `ranger` to save window-config 00c2b48d5d0f389d09a04c28be166d41044de97d

**Comment by justbur** [comment]
What's the intended behavior? Sorry but I'm not seeing the difference

**Comment by punassuming** [comment]
@justbur, Right now I hook into window-configuration-change-hook to cleanup ranger windows when leaving.  Let me know if you find any bugs

**Comment by justbur** [comment]
Seems much better now. Thanks!
