### ISSUE TITLE
C-h shows history buffer

### ISSUE THREAD

**Issue by justbur** [punassuming/ranger.el#25]
I'm not sure if this is specific to spacemacs, but if I hit C-h in ranger I get a helm buffer titled ranger-history. This doesn't seem intended, but if it is I don't think you should shadow C-h for all of the help information that becomes unavailable.

**Comment by punassuming** [comment]
@justbur, That was intentional but not well thought out.   Do you have a suggestion for a better keybinding for ranger-history?

**Comment by punassuming** [comment]
@justbur , I updated the map to `zz` for history prompts

**Comment by justbur** [comment]
Thanks. The main problem was that I had no way of learning the key bindings
through emacs with C-h taken.

I think dired shows a hint for key bindings when you press ?. Any chance
you could provide a ranger version of that? I didn't check, so sorry if you
already have.

**Comment by punassuming** [comment]
Yeah,  I updated `?` But will make it more robust later

**Comment by justbur** [comment]
Nice. I'll check it out later.
