### ISSUE TITLE
l (lowercase L) and h do not always work

### ISSUE THREAD

**Issue by justbur** [punassuming/ranger.el#26]
I'm trying to figure out why, but occasionally I get "stuck" in the dired map where l and h just move the cursor left and right instead of going up and down directories. For what it's worth RET still works in this case.

**Comment by punassuming** [comment]
@justbur, I found an issue today where preview window was erroring out due to file permissions.   I will have a fix submitted for that by tonight.

**Comment by punassuming** [comment]
@justbur, let me know if you still have this issue.

**Comment by justbur** [comment]
It was working last time I checked I think so you can close it.
