### ISSUE TITLE
Add Emacs version dependency.

### ISSUE THREAD

**Issue by Malabarba** [punassuming/ranger.el#27]
According to [this comment](http://emacs.stackexchange.com/questions/14424/tree-mode-view-selected-file-preview-in-right-side-window#comment22143_14424) `dired-hide-details-mode` is only available on Emacs 24.4 or above. If that's the case, this package should add a `(emacs "24.4")` to its `PackageRequires` header.

**Comment by punassuming** [comment]
Thanks for catching this, I will see if I can hack around a fix for <24.3 as well.
