### ISSUE TITLE
Incompatible with spacemacs evilify macro

### ISSUE THREAD

**Issue by x-ji** [punassuming/ranger.el#30]
Seems that it won't automatically change preview buffer as I move through different files, and I have to press `i` twice to preview the new file? Not sure if that's the intended behavior or that I didn't enable some configuration. I think in the original Ranger, preview updates automatically when you move to a new file.

**Comment by punassuming** [comment]
It should update previews.  Are you using melpa or melpa stable? Evil mode or emacs?  Wgat keys are you using to traverse?  J and K?

**Comment by x-ji** [comment]
I'm using `spacemacs` and I just installed Ranger by including the contribution layer.

**Comment by x-ji** [comment]
Instead of pressing `i` twice, I can also get Emacs to show the file by `L`, but still it doesn't automatically preview the file.

**Comment by punassuming** [comment]
Which editing mode in spacemacs are you using?  Evil,  emacs,  or the new hybrid?

**Comment by x-ji** [comment]
Evil. And the "Dired by name" buffer used by Ranger shows "EVILFIED" when I open it.

**Comment by punassuming** [comment]
OK, I can confirm that the latest changes in spacemacs definitely break ranger now.  I will look into how `evilify` has changed.  @syl20bnr, do you have any idea where I can start off looking?

**Comment by syl20bnr** [comment]
I'm using ranger and I don't see anything that looks like what @x-ji describes. The state is normal, pressing `i` works as expected.

@x-ji What version of spacemacs are you using ? Do you have any custom config that could be related with evilified state ?

**Comment by punassuming** [comment]
@syl20bnr, I think I found the culprit.  The `vinegar` contrib evilifies `dired-mode`, which seems to supercede the ranger-mode-map that is defined in `ranger`.  The two fixes I can think of are to modify vinegar to not use evilify, or to find a way to get the ranger-mode-map to be the topmost binding.  Which is the suggested way?

Disabling `vinegar` fixed the issue for me at least.

**Comment by punassuming** [comment]
Further looking into it I was able to revert the evilified state by adding the following to the ranger-mode section: 

```
    (defun disable-evilified-state ()
      (evil-evilified-state -1))
    (add-hook 'ranger-mode-load-hook 'disable-evilified-state)
```

... nevermind, this breaks all evil mappings.

**Comment by punassuming** [comment]
Ranger now uses emacs-state.  Should allow dired and vinegar to function without issue when in normal or evilified state.
