### ISSUE TITLE
Spacemacs - `pp` after marking files with `dd` just moves the cursor up one line.

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#37]
I can't move a file after marking it with `dd`.  Pressing `pp` just moves the cursor.

**Comment by punassuming** [comment]
I will check it out tonight. Does yy work for copying files?

**Comment by synic** [comment]
`yy` did work, and now `dd` is working.  I didn't change anything, so I guess I'll watch and see if it happens again.

**Comment by punassuming** [comment]
If it happens again, press `p?` with the latest commit to see what is in the copy ring.

**Comment by punassuming** [comment]
@synic, have you seen this again?

**Comment by synic** [comment]
No I have not.  I will close and reopen if I see it again.
