### ISSUE TITLE
Question - Is there a way to open files in a split?

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#38]
Is there a way to open files in a horizontal or vertical split?

**Comment by punassuming** [comment]
Do you mean opening marked files from within Ranger?

**Comment by synic** [comment]
Well, that information would be useful too.  

What I mean is like what NeoTree does with `-` and `|`.  If you have one file open, open neotree, and press `-` on a file, that file will be opened in a new vertical split window, and `|` opens it in a horizontal split window.

**Comment by punassuming** [comment]
The way we latch onto window configuration changes makes this difficult to predict the result.  I will give it a try in the post exit hook and see if we can try something similar.

**Comment by punassuming** [comment]
Latest commits open up commands for splitting (`ws` / `wv`) and new frame `wf`.  Thanks for the ideas!

**Comment by synic** [comment]
Wow, that's awesome.  Thank you!
