### ISSUE TITLE
Disable preview by default

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#39]
I'd like to disable the preview by default.  In my spacemacs config I have this:

```
     (ranger :variables
             ranger-show-preview nil)
```

in my .spacemacs `dotspacemacs-configuration-layers`, however, it always opens with the preview enabled by default.  I'd like to also disable showing dotfiles on startup as well, but it seems those initialization parameters don't work like that.

**Comment by punassuming** [comment]
The correct variable you want is 

```
(ranger :variables
             ranger-preview-file nil)
```

**Comment by synic** [comment]
Ah, thank you!
