### ISSUE TITLE
Add tab support

### ISSUE THREAD

**Issue by punassuming** [punassuming/ranger.el#4]

**Comment by wasamasa** [comment]
Wouldn't it suffice to use one of the numerous workspace packages and allow one to copy/cut/paste between the "views" (for the lack of a better word) of ranger.el?

I wrote [eyebrowse](https://github.com/wasamasa/eyebrowse) to have something like ranger's tabs in Emacs, but have extended it to feel more like tmux, Vim or i3, depending on what you fancy. Other possible alternatives would be perspective.el, elscreen/escreen and workgroups/workgroups2, I've described them briefly in the "Alternatives" section in my README.

**Comment by punassuming** [comment]
@wasamasa I have used eyebrowse in spacemacs, but hadnt thought much about external packages.   I agree that there are many other "tab"  managers,  but we really need a simple manner of just holding a list of navigated directories in tabs and allow traversal through them by clicking the spot on the primary window header line,  or by keybinding.   I am afraid that any complex packages would need to be hacked a bit to fit this simple need.   Granted I am sure they are all written better than I would be able to.

**Comment by psamim** [comment]
+1

**Comment by punassuming** [comment]
Tab support @wasamasa @psamim, tab support is added in latest commits.
