### ISSUE TITLE
ranger-show-dotfiles set to nil, ranger.el sets it back to t

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#41]
In my config:

``` elisp
     (ranger :variables
             ranger-show-dotfiles nil
             ranger-preview-file nil)
```

The preview line works, but `ranger-show-dotfiles` is reset to `t` after I open ranger for the first time.

I've also tried the following:

``` elisp
  ;; tell ranger not to show dotfiles initially
  (setq ranger-show-dotfiles nil)
  (eval-after-load "ranger"
    '(progn
       (setq ranger-show-dotfiles nil)
    ))
```

In my `dotspacemacs/user-config` section.  If I open ranger, I can still see dotfiles.  If I run `describe-variable` on `ranger-show-dotfiles`, it shows that it is `nil`.

**Comment by punassuming** [comment]
Yes,  good catch,  I dont have an initial check for that variable.  I will add one

**Comment by punassuming** [comment]
Latest commit fixes it.

**Comment by synic** [comment]
Thank you, that's awesome

**Comment by synic** [comment]
This still seems to have some issues.  If I open ranger, the pane on the left will show dotfiles, but the pane on the right won't.  If I press `h` to go back, the pane that was on the left is now on the right, but dotfiles aren't showing.  

It seems like the initial state still isn't set correctly.

**Comment by punassuming** [comment]
I wasnt updating the parent folders.  I have a fix I will push tonight

**Comment by punassuming** [comment]
14406b6e3f12df03296080519fcbecb88dfe880d should address it.  Let me know if you see other issues.

**Comment by synic** [comment]
Yup, it's working great now.  Thanks
