### ISSUE TITLE
Question - Can I replace dired with deer?

### ISSUE THREAD

**Issue by synic** [punassuming/ranger.el#49]
I've been trying my hand at emacs lisp, but unfortunately it's not working quite right.  Maybe you can help?  I'm trying to replace dired with deer as the default directory handler.  I've got the following function:

``` elisp
(defun deer-find-file (&optional entry ignore-history)
  "Find file in deer buffer. `ENTRY` can be used as a path or filename, else
will use currently selected file in ranger. `IGNORE-HISTORY` will not update
history-ring on change."
  (interactive)
  (setq ranger-minimal t)
  (ranger-find-file entry ignore-history)
  )
```

And then, in my config, I have this:

``` elisp
  (setq find-directory-functions '(deer-find-file cvs-dired-noselect dired-noselect))
```

Unfortunately, when I try to open a directory, it says: 

```
eval: Lisp nesting exceeds `max-lisp-eval-depth'
```

**Comment by punassuming** [comment]
@synic, I will try to figure out how to do this.  The one complication I see is that I have most of the ranger variables globally defined,  so multiple deer or ranger windows will likely not work.   I can look into window specific variables to store all this data,  but haven't had the need to until recently when I fixed frame checking behaviour.   

Another thing you can try is to add a hook to dired-mode-hook or dired-mode-load-hook to open ranger after loading the dired buffer.

**Comment by punassuming** [comment]
@synic, added PR in spacemacs to work this way.  https://github.com/ralesi/spacemacs/commit/6bbaade698da96ad87377dbd9024ac00b965391e

**Comment by synic** [comment]
Hrmm, it doesn't seem to work like I expect - maybe I'm going about this the wrong way.  The project links on the homepage are nice, but they open in `dired`.  Typing `:e ~/` opens `dired` (but not always, this seems to change every time I type it).  These are the behaviors I want to change - maybe I need to change them in spacemacs instead of in ranger.

I really only want to use one filemanager, but if I can replace it in those contexts, it should be sufficient.

**Comment by punassuming** [comment]
@synic, No it doesn't, I am cancelling PR and adding options into ranger specifically.

**Comment by synic** [comment]
ok!  Thank you.

**Comment by punassuming** [comment]
@synic, commit is in setting is ranger-override-dired.

**Comment by synic** [comment]
Yay, it works!  Thank you thank you.
