### ISSUE TITLE
Error during redisplay: ranger-header-line

### ISSUE THREAD

**Issue by igorepst** [punassuming/ranger.el#58]
Hi, with ranger 20151005.119, in deer-mode I constantly get `Error during redisplay: (eval (ranger-header-line)) signaled (args-out-of-range #("/home/vasya/.emacs.d/.git                                                .. / 1 " 21 25 (face font-lock-constant-face) 73 80 (face font-lock-comment-face)) 0 82)`

**Comment by punassuming** [comment]
I have a fix for this that I will post shortly

**Comment by punassuming** [comment]
The issues with the headerline should be resolved.

**Comment by igorepst** [comment]
Working, thanks
