### ISSUE TITLE
dired-listing-switches

### ISSUE THREAD

**Issue by igorepst** [punassuming/ranger.el#59]
Hi, I would like, please, to use custom dired-listing-switches. Could you, please, move them to defcustom, like it's shown in the code comment? Thank you

**Comment by punassuming** [comment]
@igorepst, What code comment are you referring to?  Would you like a custom sort option for this, or are these non sorting switches you would like? Can you give me an example?

**Comment by igorepst** [comment]
I would like to use
`(setq dired-listing-switches (purecopy
                (concat "-AhFlv --group-directories-first"
                    " --time-style=+%d/%m/%y" (string ?\u2008) "%R")))`
`(setq directory-listing-before-filename-regexp
    (purecopy (concat "\\([0-2][0-9]:[0-5][0-9] \\)\\|" directory-listing-before-filename-regexp)))`
Please see the discussion [here](http://emacs.stackexchange.com/questions/2722/dired-listing-switches-time-style-format-with-a-space/17109#17109)
I meant the code in `ranger-setup` that overrides this:
`;; hide groups, show human readable file sizes
  ;; TODO add as defcustom
  (setq dired-listing-switches "-alGh")`

**Comment by punassuming** [comment]
@igorepst  Just added dired listing options for ranger.  I don't use `ls` since I am running ms-windows, but have a routine to sort the dired buffer with directories first.  Does this work with standard `ls`, or do you still need the `--group-directories-first` command?

**Comment by igorepst** [comment]
It works... partly (all is well until I try to sort via Ranger). I would like to test it further in the coming days

**Comment by punassuming** [comment]
Can you put the "-AhFlv term at the end?,  this way the sort option will append to this term.  I will check if I can make the sorting terms a separate argument so it won't interfere.

**Comment by igorepst** [comment]
With `--group-directories-first` and `-AhFlv` at the end it seems to work mostly well with sorting. But both in ranger and in deer I eventually see in the modeline after sorting the same directory by various parameters, that the modeline includes something like the following: "Ranger: --group-directories-first --time-style=+/Ranger: --group-directories-first --time-style=+/Ranger: --group-directories-first --time-style=+%d/%m/%y %R -AhFlv**t**". Now, it may be a bug in spaceline mode I use or in Ranger. I cannot check the code right now, but will do in the coming days. Thank you very much!

**Comment by punassuming** [comment]
That will be something I need to fix.  Right now with all the sorting possibilities,  the modeline will show the listing switch if it doesnt match any other regex matches.   I will change that to showing "custom"  instead

**Comment by igorepst** [comment]
I meant there are repetitions in the modeline. Perhaps, the switches are added more than once, perhaps, not

**Comment by igorepst** [comment]
OK, the problem lies somewhere in `powerline` package, the `spaceline` is based on, and not in the `Ranger` code. Thank you

**Comment by igorepst** [comment]
I thought the problem is in `powerline` package, the `spaceline` is based on, but I'm not sure anymore. Will leave it closed for now. Thanks!
