### ISSUE TITLE
Define ranger-mode-map at init/config time

### ISSUE THREAD

**Issue by StreakyCobra** [punassuming/ranger.el#78]
I have a special keyboard layout, and I'm rebinding the evil `hjkl` keys to the equivalent keys on my keyboard. I've already written a Spacemacs layer for this, but I can't make it work for `ranger.el`. After looking with @TheBB, it's because the map [is defined when entering the mode](https://github.com/ralesi/ranger.el/blob/master/ranger.el#L2166), and not at init/config time. Also because of this, changes will be overwritten each time the mode is entered.

**Comment by punassuming** [comment]
@StreakyCobra, I am doing a major overhaul of the internals as ranger is getting too bulky now, but will try to get this done quickly.

**Comment by StreakyCobra** [comment]
Thanks for your help, take your time :smile:

**Comment by punassuming** [comment]
What is your preferred way to configure?  Do you want to apply with a hook or place preferred settings in :init or :config?

**Comment by StreakyCobra** [comment]
I don't really like the hook way, because bindings get recreated each time the mode is entered, so if an user want to customize bindings, it has to be in the hook too, and order in there is important and... I don't really like it. The better for me is at `init` or `config`, and I like to think: "The sooner the better", but I'm not really an elisp expert so... maybe there are drawbacks.

If you want to see how I do the remapping, here is the code on which I'm currently working:

https://github.com/StreakyCobra/spacemacs/blob/contrib/bepo/layers/%2Bkeyboard-layouts/bepo/keybindings.el

The important thing to look at is the `:loader` parts, where `BODY` represent the place where the actual rebinding will be placed. Most of them are run in `:post-init` and `:post-config`.

**Comment by punassuming** [comment]
@StreakyCobra, I just submited a new branch called https://github.com/ralesi/ranger.el/tree/proper_keymap.  If you get a chance, can you try this and see if this way of mapping the bindings works?  If so I will clean it up and add it to master.

**Comment by StreakyCobra** [comment]
Sorry for the delay. I can indeed rebind keys with a `post-config` hook on the `proper_keymap` branch :+1:

Neverthless I have a problem with your map that I don't have with other ones. Let me explain.

For switching several keys at once (e.g. "t" -> "j", "j" -> "t"), I need to keep a temporary copy of the original keymap. For this I use `copy-tree`. As it's a copy, modifying `ranger-mode-map` shouldn't modify it. Sadly it does. Here is an example to let you test:

``` elisp
;; Copy the ranger-mode-map to original-map
(setq original-map (copy-tree ranger-mode-map))
;; Look for the binding of "t" in ranger-mode-map
(lookup-key ranger-mode-map "t")
;; Verify the binding is the same as in ranger-mode-map
(lookup-key original-map "t")
;; Change the binding of "t" in ranger-mode-map, should not modify original-map
(define-key ranger-mode-map "t" 'ranger-next-file)
;; Verify the change really happened
(lookup-key ranger-mode-map "t")
;; Should not have been changed in the copy… WRONG
(lookup-key original-map "t")
```

But it works with all other keymaps that I use, like `evil-normal-state-map`:

``` elisp
;; Copy the evil-normal-state-map to original-map
(setq original-map (copy-tree evil-normal-state-map))
;; Look for the binding of "t" in evil-normal-state-map
(lookup-key evil-normal-state-map "t")
;; Verify the binding is the same as in evil-normal-state-map
(lookup-key original-map "t")
;; Change the binding of "t" in evil-normal-state-map, should not modify original-map
(define-key evil-normal-state-map "t" 'ranger-next-file)
;; Verify the change really happened
(lookup-key evil-normal-state-map "t")
;; Should not have been changed in the copy… RIGHT
(lookup-key original-map "t")
```

Do you know why it's different? And if yes do you have a way to make this possible?

**Comment by punassuming** [comment]
@StreakyCobra , give it a try now.  I was defining the keymap improperly with `make-keymap` instead of `make-sparse-keymap`.  With the changes now, in your example above, `original-map` retains the original now.

**Comment by StreakyCobra** [comment]
@ralesi Seems to be working :smile: :+1: I had to add `:commands (ranger)` in use-package to make it work though, and there is an error thrown from you code:

``` text
Debugger entered--Lisp error: (void-variable ranger-mode-map)
  (define-key ranger-mode-map ranger-key (quote ranger-mode))
```

The two are drawbacks are maybe related though, as the error come from an autoload:

``` elisp
;;;###autoload
(when ranger-key
  (with-eval-after-load "evil"
    (evil-define-key 'normal dired-mode-map ranger-key 'ranger-mode))
  (define-key ranger-mode-map ranger-key 'ranger-mode))
```

**Comment by punassuming** [comment]
@StreakyCobra Yep,  I will figure out where to fit that guy. I need to define at the beginning,  before ranger is loaded so we can toggle it.   I can fix that.   Once done I will incorporate into master.   One other thing I added in this branch that you might try is a prefix for dired,  using ;.   Now you can run standard dired bindings that might be mapped over by the ranger bindings. Like w,  c,  or m.

**Comment by StreakyCobra** [comment]
:+1: Cool, thx for your help :-)

For the dired stuff, I'm not used to it, so I'll probably not use it anyway :-p

**Comment by punassuming** [comment]
@StreakyCobra , updated changes to master.

**Comment by StreakyCobra** [comment]
Yep I saw it was done when I saw this: https://github.com/syl20bnr/spacemacs/issues/3910 :stuck_out_tongue: I put a comment for you there, if you can help.

I'm closing this one as is should be solved now, thx!
