### ISSUE TITLE
ranger exiting after i open/view a file?

### ISSUE THREAD

**Issue by zeltak** [punassuming/ranger.el#81]
Hi

i used to use ranger alot a few years ago (way before i discovered emacs!) and was really excited to see someone made an emacs ranger! thx so much for your excellent work!

i have a silly question. why does the ranger buffer auto close when i view/launch a file?  in example when i press/open a pdf it opens the opens it in docview but when i close the docview buffer the ranger buffer is gone?

btw, do you aim at feature parity with ranger down the road?

thx so much

Z

**Comment by punassuming** [comment]
I dont think I will ever make it to feature parity,  but which features would you like / need?   In terms of your issue,  this is the way ranger.el has been created,  in the version,  we are more editing centric than the real ranger.   There are ways I can show you to more easily access ranger from a file,  but currently when opening a file,  we close the existing ranger session.

**Comment by zeltak** [comment]
thx for the answer, ill use ranger of the next few days and compile a list of things i miss :)
one thing related i guess is if dired commands work at all within ranger. for example i tried pressing `0w` to copy a path name but that didnt seem to work

finally, do you think i can make a feature request to have an option to leave ranger buffer open (constantly) or is that technically not possible?

thanks so much for all your hard work, i really enjoy ranger

z

**Comment by punassuming** [comment]
@zeltak, are you using this within evil or emacs state?   w is currently use to open files and keep ranger open like `wf` to open in new frame.     What would be the ranger way of using 0w?  I am also working on making an option for dired style bindings.

**Comment by zeltak** [comment]
Hi again

no im using it from normal emacs modes (i dont use evil). the ranger way of doing it was to assign a user defined key to a xclip command ;-)
but i love the internal dired 0w command that does just that and works across all Os/distros. just thought it would be cool to leverage existing dired magic into ranger :)

thx so much again, im really enjoying using ranger past few days!

Z

**Comment by punassuming** [comment]
@zeltak, I just submitted a change to my proper_keymap branch that includes a prefix map for dired.  This will allow you to Press `0 ; w` to copy the filename now.

**Comment by zeltak** [comment]
ralesi

i just updated from melpa and it seems to work (kinda :))

in dired i get the file+path. now in ranger i get this

  /home/zeltak/ZH_tmp:  total used in directory 2.0G available 63121356

which is the path only and some info on the dir size, can you confirm?

thx!

Z

**Comment by punassuming** [comment]
@zeltak, I can confirm that the ring has additional information.  It appears I am contaminating the ring on movement.

**Comment by punassuming** [comment]
@zeltak I fixed the issue in recent version.

**Comment by punassuming** [comment]
@zeltak, let me know if you ever put together that last of things you were missing in this version of ranger.
