### ISSUE TITLE
Evil Rebindings Overwritten

### ISSUE THREAD

**Issue by noctuid** [punassuming/ranger.el#85]
This is somewhat related to things mentioned in #78. I expect this to work:

```
(evil-define-key 'normal ranger-mode-map
  "n" 'ranger-next-file
  "k" 'evil-search-next
  "K" 'evil-search-previous)
```

It looks like `ranger-define-additional-maps` is called every time ranger mode starts, so any user-defined keybindings are overwritten. I think it would be nice if evil keybindings are only created once (when ranger.el is loaded).

It is possible to work around this by using `ranger-mode-hook`, but I think this behavior is unexpected.

**Comment by punassuming** [comment]
I will revise and combine emacs and evil search functionality together in a single command so that I can make a single binding in ranger-mode-map.

**Comment by punassuming** [comment]
@noctuid, I have moved the bindings all within the ranger-mode-map definition,  you should be able to overwrite bindings now.

**Comment by vyp** [comment]
Thanks @ralesi!

**Comment by noctuid** [comment]
@ralesi It is not working for me using the example I originally posted.

**Comment by punassuming** [comment]
@noctuid, what state is ranger in when you run the evil-define-key? I.e. are you requiring ranger first, or using from use-package?

**Comment by noctuid** [comment]
Neither works (using `evil-define-key` before or after requiring ranger) with the latest version from melpa, but I'd expect both to work. Now the `evil-define-key` statement never works, whereas before I could use `ranger-mode-hook` to make it work.

**Comment by punassuming** [comment]
@noctuid,  Is there a reason you are defining it with `evil-define-key` rather than just `define-key`?   I am able to rebind keys after loading with `define-key`.   Also,  I moved ranger to use motion state when evil is loaded so as not to interfere with the dired mode hooks in `evil-integration.el`.

**Comment by punassuming** [comment]
I do not currently autoload `ranger-mode-map`, so defining maps prior to requiring ranger shouldn't work.

**Comment by noctuid** [comment]
Alright thanks, I'll just change the initial state back to normal.

> Is there a reason you are defining it with evil-define-key rather than just define-key?

I use `evil-define-key` for defining any non-global keybindings. Evil's key definition functions are far more convenient and versatile.

> I do not currently autoload ranger-mode-map, so defining maps prior to requiring ranger shouldn't work. 

It should and does. I just didn't realize motion state was being used now.  `evil-define-key` works regardless of whether the keymap has been initialized.
