### ISSUE TITLE
Go back to the window layout after editing a file

### ISSUE THREAD

**Issue by c02y** [punassuming/ranger.el#86]
For example, I was navigating inside of ranger, and then I `Enter` at a file and edit it(this will make the file into the full frame), how can I go back to the ranger state before editing the file or can I edit it directly instead of making the file into the full frame? 

I know I can use `ranger-show-history` to go back to that state, but it will give a prompt, so is there any simpler way to go back to the window layout after editing a file?

**Comment by vyp** [comment]
#81 related I think.

**Comment by c02y** [comment]
Thanks, `wf`

**Comment by vyp** [comment]
Doesn't that open in a separate frame though?

**Comment by c02y** [comment]
That's the best command I can pick from that issue, not the exact feature I want though.

**Comment by vyp** [comment]
Yeah I figured. I linked because it seems you both want the same sort of thing.

**Comment by punassuming** [comment]
@c02y So when you exit a few things happen,  but when running ranger it should bring the window layout back to ranger in the current directory.   Is this not what is seen? 

Do we just need an accessible keybinding to open ranger from anywhere?

**Comment by punassuming** [comment]
@c02y and @zeltak, these seem similar,  but I am not sure I am getting the issue.   You want to be able to browse with ranger,  open a file,  then close it and be back in ranger?  Can't we just run `ranger` directly to jump to ranger in the current working directory?  Do we need an externally defined command for running ranger?

**Comment by c02y** [comment]
When I am editing an file from ranger, after killing the buffer, Emacs will restore into the previous ranger layout automatically (I do not need to type command ranger again), this is the best way, exactly like ranger command in a terminal, exit the file and back to ranger.

**Comment by punassuming** [comment]
@c02y, the develop branch has a new option: ranger-return-to-ranger that when non-nil,  will return to ranger when the current buffer is deleted.
