### ISSUE TITLE
Open with external program

### ISSUE THREAD

**Issue by psamim** [punassuming/ranger.el#87]
Hi,
Is it possible to open a file with an external program?
Thanks

**Comment by punassuming** [comment]
All that is currently set up is `we` to open in the default external application for the file type.  Is that what you were looking for?

**Comment by psamim** [comment]
Yes, that is exactly what I was looking for. I found that shortly after in the source code, but the documentation lacks this feature. I made a pull request adding the missing docs for these key bindings.

Thanks

**Comment by punassuming** [comment]
Awesome! That is one of the things I have struggled to keep up with, thank you.

**Comment by punassuming** [comment]
I merged your commit,  thanks for the help!
