### ISSUE TITLE
Option to show or hide details

### ISSUE THREAD

**Issue by psamim** [punassuming/ranger.el#93]
Hi,
It would be very helpful to have an option to hide file details as in http://www.emacswiki.org/emacs-test/DiredDetails .

**Comment by punassuming** [comment]
@psamim, are you referring to when in deer mode, since ranger already uses it?

**Comment by psamim** [comment]
This screenshot is my ranger in spacemacs and I can see the details.

![2016-01-13-22 22 53](https://cloud.githubusercontent.com/assets/1868679/12304418/b6d5a952-ba44-11e5-9fa9-7b5fdf0841fd.png)

**Comment by psamim** [comment]
My mistake, I saw it. It shows the details in the preview and hides the details otherwise.

Thanks

**Comment by punassuming** [comment]
@psamim, do you want an option to disable details in deer mode as well?

**Comment by psamim** [comment]
That would be a nice feature.

**Comment by punassuming** [comment]
@psamim, `zd` will now hide details in deer.

**Comment by psamim** [comment]
@ralesi Thanks! Works here nicely on Spacemacs.
