### ISSUE TITLE
select the correct parent directory after pressing "h" or "l"

### ISSUE THREAD

**Issue by adrianstaniec** [punassuming/ranger.el#97]
when going to child directory "l"
the cursor/highlight does not remain at the previously visited directory (in the collumun to the left)

and 

when going to the parent directory "h"
the cursor is not located at the directory  which I came from

**Comment by punassuming** [comment]
@adrsta, can you give me the steps you go through to get this behavior? Does it occur with every transition?

**Comment by adrianstaniec** [comment]
ok, it's pretty straight forward, let's say:
0. I start in ~
1. I use `j` and `k` to navigate to .emacs.d and press `l`
2. I am in .emacs.d so that's good, but the "cursor" in the colum to the left (parent column) does not highlight .emacs.d but Documents directory for some reason (weird)
3. I press `h` to go back to ~, and it happens, but my cursor is on Documents and not on .emacs.d

if you check original ranger, it behaves differently

**Comment by punassuming** [comment]
@adrsta, I understand the problem, and I agree this isn't the intended behaviour.  The reason I asked is that I do not see this behavior.  When I navigate up to a parent directory or go into a directory in ranger, the parent window has correct folder highlighted.  

The mention of `Documents` makes me think this might be something to do with symlink referencing.   Is emacs.d symlinked to home?  Does this behaviour occur outside of the emacs.d directory?  For instance do you see this when navigating within the emacs.d/elpa/ directories?

**Comment by adrianstaniec** [comment]
mhm, in that case I guess it's not going to be so easy to fix
strange, because, I see this behaviour all over the place

I am not sure about the symlinks,
I think the `Documents` is just a regular directory not a link

and it also changes,
I mean now (after closed and opened ranger few times)
it comes back to another directory in my ~

it could have something to do with:
- the previously visited directories or
- recent files or
- openened buffers
  I'm guessing

**Comment by punassuming** [comment]
@adrsta, can you let me know your emacs build and OS? I normally work in windows, but cab try it on my linux box.

**Comment by adrianstaniec** [comment]
I am on:
Debian GNU/Linux 8.3 Jessie
GNU Emacs 24.4.1 (x84_64-pc-linux-gnu) 2015-03-07 on trouble, modified by
Debian
Spacemacs v.0.105.9

**Comment by duerrp** [comment]
I have the same issue as OP, but only when I use ranger in terminal emacs. Under X it is working as advertised...

**Comment by punassuming** [comment]
@duerrp, I will try this out on my rpi and see what the issue is.

**Comment by duerrp** [comment]
@ralesi Thanks!

**Comment by adrianstaniec** [comment]
Thank you! :+1:
