### ISSUE TITLE
can't go up past my home directory

### ISSUE THREAD

**Issue by adrianstaniec** [punassuming/ranger.el#98]
1. I have a buffer open that is in /home/username/dir1/dir2/file.txt
2. I open ranger
3. I repeteadlykeep pressing `h`
4. I cannot reach /root , but go only up to /home/username

**Comment by punassuming** [comment]
@adrsta, this one is odd too, never heard of this bug.  What happens when you edit a file in /etc and then open ranger, can you navigate in that directory?

**Comment by adrianstaniec** [comment]
than it works fine, I can navigate to root
I only have the problem when starting the ranger when buffer is located in ~ tree,
and it only stops in my ~

**Comment by punassuming** [comment]
Ok,  I think I know the issue then.  Thanks,  will have a fix soon.

**Comment by adrianstaniec** [comment]
Thank you! :+1: You are awesome!
