### ISSUE TITLE
How to create a new file

### ISSUE THREAD

**Issue by psamim** [punassuming/ranger.el#99]
Hi,

When I am in dired and evil, I use `:e <FILE>` to create a new file in the current directory, but I do not know how to create a new file when visiting a directory in ranger.

Thanks

**Comment by psamim** [comment]
I found out that same thing can be done using `f` (find file). But the problem is that `f` is shadowed by evil-mode. I use Spacemacs. I think I should report the problem there.

**Comment by psamim** [comment]
Created https://github.com/syl20bnr/spacemacs/issues/5029

**Comment by punassuming** [comment]
@psamim,  is this resolved with the fix for evil-snipe in spacemacs?

**Comment by punassuming** [comment]
Reopen if you still see an issue
